import type { Locale } from '@/i18n/routing';

/**
 * The question set, grouped the way the help centre of a booking site groups
 * it, but answered for a business that takes enquiries rather than payments.
 *
 * Every answer here has to survive being true. Where we do not yet know a
 * thing, the answer says so rather than inventing a policy: this is a specimen
 * catalogue, and a fabricated refund window is a fabricated record.
 */

export type QA = { q: string; a: string };
export type FaqCategory = { id: string; title: string; blurb: string; items: QA[] };

const EN: FaqCategory[] = [
  {
    id: 'prices',
    title: 'Prices and what is included',
    blurb: 'What the number means before you ask us anything.',
    items: [
      { q: 'Is the price per person or for everybody?',
        a: 'Every figure on a trip page is the whole price for the party you set. Change the traveller count and the number moves with it. We also show the per-person and per-night figures underneath, so you can compare trips of different lengths honestly.' },
      { q: 'Are taxes and fees already in the price?',
        a: 'Yes. Mandatory taxes and fees are computed into the figure before you see it. There is no step later where the total grows.' },
      { q: 'Then what is the "not included" list for?',
        a: 'Things that are genuinely outside the package: a visa fee, a hold bag on a carrier that charges for one, an airport transfer where none is contracted. Each one is named and carries an estimate and where that estimate came from. We would rather you saw it here than at the end.' },
      { q: 'Why does the price change when I change the number of nights?',
        a: 'Because it stops being the trip we sell. A package is a contracted set of nights, so the moment you move off that length the figure becomes an estimate, calculated from the nightly rate, and it is labelled as one. A person confirms the real number before anything is committed.' },
      { q: 'Do you show a crossed-out "was" price?',
        a: 'No. We do not display a reference price we never charged, and we do not run countdown timers or "three people are viewing this" counters. If a departure is genuinely limited we will tell you the real number.' },
      { q: 'Which currency am I seeing?',
        a: 'The currency of the city you fly out of. A trip from Kuwait is priced in Kuwaiti dinar, which carries three decimal places, and we render it with three rather than rounding it to two.' },
    ],
  },
  {
    id: 'enquiry',
    title: 'Enquiring and quotes',
    blurb: 'What happens between you asking and you deciding.',
    items: [
      { q: 'Can I book online right now?',
        a: 'No, and that is deliberate rather than missing. You send an enquiry, a person picks it up and comes back to you with a firm quote. Nothing on this site takes payment.' },
      { q: 'Does it cost anything to enquire?',
        a: 'No. There is no charge at any point on this website.' },
      { q: 'What do I get back, and when?',
        a: 'A written quote for the party and dates you asked about, with the same all-in figure and the same exclusions list you saw on the page. Response times depend on the hours we publish rather than a promise we cannot keep.' },
      { q: 'How long does a quote hold?',
        a: 'Every quote carries a visible expiry. When it lapses the page does not disappear; it shows the same quote struck through with a way to ask for a fresh price.' },
      { q: 'Am I committed once I enquire?',
        a: 'No. An enquiry is a question. Nothing binds you until you are given terms and you accept them in writing.' },
      { q: 'Can we talk on WhatsApp instead of filling in a form?',
        a: 'Yes, and it is the way most of this works. The trip, your dates and your party come through with the message, so you do not have to type them again.' },
    ],
  },
  {
    id: 'changes',
    title: 'Changes, cancellation and refunds',
    blurb: 'What happens when plans move.',
    items: [
      { q: 'Can I change the dates or the group after enquiring?',
        a: 'Before anything is confirmed, yes, freely — tell us and we requote. After confirmation it depends on the suppliers behind that trip, and the quote states those terms before you accept.' },
      { q: 'What is the cancellation policy?',
        a: 'Each trip carries a dated refund ladder rather than a paragraph in a PDF: a percentage that changes as your departure gets closer. It is computed against your own departure date, so you can see exactly where you stand on any given day.' },
      { q: 'How long does a refund take?',
        a: 'That depends on the supplier and the payment route, and we will not publish a median we cannot yet evidence. We will give you the expected window in writing with your terms.' },
      { q: 'The airline changed my flight time. What do I do?',
        a: 'Tell us. Schedule changes come from the carrier, and what you are entitled to depends on how large the change is. We handle the correspondence.' },
      { q: 'Something went wrong on the trip. Who do I complain to?',
        a: 'The person who handled your booking, first. If that does not resolve it, ask for it to be escalated and we will tell you who is handling it and by when.' },
    ],
  },
  {
    id: 'documents',
    title: 'Visas, passports and documents',
    blurb: 'The part that causes the most anxiety, answered per passport.',
    items: [
      { q: 'Do I need a visa?',
        a: 'It depends on the passport you hold, not on where you live. Each trip page states the visa position for the destination with the date it was last checked, because these rules change without notice.' },
      { q: 'Why is the visa listed as "not included" when it costs nothing?',
        a: 'Because "not included" means outside the package, not necessarily expensive. Where a destination is visa-free on a Gulf passport we list it at zero and say so, rather than leaving it off the list and letting you wonder.' },
      { q: 'How much passport validity do I need?',
        a: 'Most destinations here want six months beyond your return date. We confirm the requirement for your specific route in the quote.' },
      { q: 'When do you ask for my passport number?',
        a: 'Not at enquiry, and not to show you a price. Document details are collected close to departure through a secure link, because holding identity documents any longer than necessary is a risk to you and to us.' },
      { q: 'Do you handle the visa application for me?',
        a: 'Where a destination allows an agency to file on your behalf we will say so on the trip page. Where it does not, we tell you what to file and roughly how long it takes.' },
    ],
  },
  {
    id: 'faith-family',
    title: 'Halal food, prayer and travelling as a family',
    blurb: 'Modelled as facts we checked, not a badge.',
    items: [
      { q: 'Is the hotel halal-friendly?',
        a: 'That is not one question, so we do not answer it with one badge. Each trip carries separate states for halal food nearby, a prayer room, whether the property is alcohol-free, and whether there is a family section. Each state names who checked it and when.' },
      { q: 'What do the green, amber and red marks mean?',
        a: 'Green is verified present. Amber is partial or conditional, and the note says how. Red is verified absent — we would rather tell you than let you find out. A grey mark means nobody has checked it yet, and we will not colour it in.' },
      { q: 'Can you find a women-only pool or beach?',
        a: 'Ask, and we will check for the specific property and date. It is a real availability question, not a permanent property of a hotel.' },
      { q: 'We are travelling with grandparents and small children. Can you handle that?',
        a: 'Yes, and the traveller control on each trip goes to twelve for that reason. Tell us the ages and who needs to be next to whom, and connecting rooms and mobility notes go into the request.' },
      { q: 'Do you sell Umrah or Hajj packages?',
        a: 'No. Both are regulated products requiring a licence from the Saudi Ministry of Hajj and Umrah, and selling them as an ordinary flight-and-hotel bundle would be a legal exposure rather than a shortcut. We will say so plainly rather than quietly take the booking.' },
    ],
  },
  {
    id: 'travel',
    title: 'Flights, bags and getting around',
    blurb: 'The mechanics of the trip itself.',
    items: [
      { q: 'Which airport do I fly from?',
        a: 'The departure city is part of the trip, not a filter you apply afterwards. Every price is computed from that city, so a trip from Jeddah and the same destination from Dubai are priced separately.' },
      { q: 'Is a checked bag included?',
        a: 'It is on the ledger of every trip, either included or listed with an estimate and its source. Carriers differ, and we do not average them.' },
      { q: 'Are airport transfers included?',
        a: 'Where they are contracted, yes, and the ledger says so. Where they are not, the ledger names them with an estimate rather than leaving them out.' },
      { q: 'Can I choose the exact hotel and flight?',
        a: 'Tell us what you want and we will price it. The catalogue is a starting point, not a fence.' },
      { q: 'Do you arrange travel insurance?',
        a: 'We will tell you what a policy needs to cover for your route. We do not sell insurance on this site.' },
    ],
  },
  {
    id: 'account',
    title: 'Your account and your data',
    blurb: 'What we hold, and what you can make us do about it.',
    items: [
      { q: 'Do I need an account to see prices?',
        a: 'No. Nothing on this site is behind a sign-in, and there is no member-only price. An account exists so you can find your enquiries again, not to unlock a number.' },
      { q: 'What do you actually store?',
        a: 'What you send us: the trip you asked about, your dates and party, and a way to reply to you. Identity documents are collected close to departure and separately.' },
      { q: 'Can you delete my data?',
        a: 'Yes. Ask, and we will confirm what has been removed and what we are obliged to retain and for how long.' },
      { q: 'Where is my data held?',
        a: 'Outside the Gulf, on managed infrastructure, because our database provider has no Middle East region. That is a disclosure rather than a footnote, and it is the honest answer to a question people do not usually get an answer to.' },
      { q: 'Do you use cookies?',
        a: 'Only what the site needs to work, unless you tell us otherwise. Declining the rest is one action and does not degrade anything you came here to do.' },
    ],
  },
  {
    id: 'about',
    title: 'About this site',
    blurb: 'What this is, honestly.',
    items: [
      { q: 'Are these real trips at real prices?',
        a: 'No, and the site says so on every card. This is a specimen catalogue: the packages are invented under an invented house brand so the design and the pricing behaviour can be shown working. Every price carries an "illustrative" mark, and nothing on the site can say "Book".' },
      { q: 'Why build it that way?',
        a: 'Because the alternative is worse. A demonstration site that shows a licence number it does not hold, or reviews from customers who do not exist, is not a weaker design — it is a fabricated record. So those are absent rather than filled in.' },
      { q: 'What does Anees mean?',
        a: 'It is Arabic. An anees is the companion who puts you at ease, from uns, the comfort of good company. It is written أنيس in Arabic and Anees everywhere else, and it is never translated into anything.' },
      { q: 'What languages do you work in?',
        a: 'Arabic and English, both written rather than machine-translated, with French in progress and marked as such in the language menu.' },
    ],
  },
];

const AR: FaqCategory[] = [
  {
    id: 'prices',
    title: 'الأسعار وما تشمله',
    blurb: 'ماذا يعني الرقم قبل أن تسألنا عن أي شيء.',
    items: [
      { q: 'هل السعر للفرد أم للمجموعة كلها؟',
        a: 'كل رقم في صفحة الرحلة هو السعر الكامل للمجموعة التي تحددها. غيّر عدد المسافرين ويتغير الرقم معه. ونعرض تحته سعر الفرد وسعر الليلة، حتى تقارن رحلات بأطوال مختلفة مقارنة صادقة.' },
      { q: 'هل الضرائب والرسوم داخل السعر؟',
        a: 'نعم. الضرائب والرسوم الإلزامية محسوبة قبل أن تراه. لا توجد خطوة لاحقة يكبر فيها المبلغ.' },
      { q: 'إذن ما فائدة قائمة «غير المشمول»؟',
        a: 'الأشياء التي تقع فعلًا خارج الباقة: رسم تأشيرة، حقيبة على ناقل يفرض رسمًا عليها، توصيل من المطار غير متعاقد عليه. كل بند مذكور ومعه تقدير ومصدر التقدير. نفضّل أن تراه هنا لا في النهاية.' },
      { q: 'لماذا يتغير السعر عند تغيير عدد الليالي؟',
        a: 'لأنها تتوقف عن كونها الرحلة التي نبيعها. الباقة عدد ليالٍ متعاقد عليه، وبمجرد أن تخرج عن هذا الطول يصبح الرقم تقديرًا محسوبًا من سعر الليلة، ونسمّيه تقديرًا. ويؤكد لك شخص الرقم الحقيقي قبل أي التزام.' },
      { q: 'هل تعرضون سعرًا مشطوبًا؟',
        a: 'لا. لا نعرض سعرًا مرجعيًا لم نتقاضه يومًا، ولا نستخدم عدادات تنازلية ولا «ثلاثة يشاهدون الآن». وإن كانت المغادرة محدودة فعلًا فسنقول لك الرقم الحقيقي.' },
      { q: 'بأي عملة أرى السعر؟',
        a: 'بعملة المدينة التي تغادر منها. رحلة من الكويت تُسعّر بالدينار الكويتي، وهو بثلاث خانات عشرية، ونعرضه بثلاث لا باثنتين.' },
    ],
  },
  {
    id: 'enquiry',
    title: 'الطلب وعرض السعر',
    blurb: 'ما يحدث بين سؤالك وقرارك.',
    items: [
      { q: 'هل أستطيع الحجز مباشرة الآن؟',
        a: 'لا، وهذا قرار لا نقص. ترسل طلبًا، ويتابعه شخص ويعود إليك بعرض سعر مؤكد. لا شيء في هذا الموقع يستقبل دفعًا.' },
      { q: 'هل إرسال الطلب مجاني؟',
        a: 'نعم. لا رسوم في أي مرحلة على هذا الموقع.' },
      { q: 'ماذا يصلني ومتى؟',
        a: 'عرض سعر مكتوب للمجموعة والتواريخ التي سألت عنها، بنفس الرقم الشامل ونفس قائمة غير المشمول التي رأيتها في الصفحة. وأوقات الرد بحسب ساعات العمل المعلنة لا بوعد لا نستطيع الوفاء به.' },
      { q: 'كم يبقى عرض السعر صالحًا؟',
        a: 'كل عرض يحمل تاريخ انتهاء ظاهرًا. وعند انتهائه لا تختفي الصفحة، بل يظهر العرض نفسه مشطوبًا مع طريقة لطلب سعر جديد.' },
      { q: 'هل ألتزم بشيء بمجرد الطلب؟',
        a: 'لا. الطلب سؤال. ولا شيء يلزمك حتى تُعطى شروطًا وتقبلها كتابةً.' },
      { q: 'هل يمكن التواصل على واتساب بدل النموذج؟',
        a: 'نعم، وهكذا يجري أغلب العمل. الرحلة وتواريخك ومجموعتك تصل مع الرسالة، فلا تعيد كتابتها.' },
    ],
  },
  {
    id: 'changes',
    title: 'التعديل والإلغاء والاسترداد',
    blurb: 'ماذا يحدث حين تتغير الخطط.',
    items: [
      { q: 'هل أستطيع تغيير التواريخ أو عدد المسافرين بعد الطلب؟',
        a: 'قبل التأكيد، نعم وبحرية، أخبرنا ونعيد التسعير. وبعد التأكيد يعتمد على المورّدين خلف تلك الرحلة، وعرض السعر يذكر تلك الشروط قبل قبولك.' },
      { q: 'ما سياسة الإلغاء؟',
        a: 'كل رحلة تحمل سلّم استرداد بالتواريخ لا فقرة في ملف: نسبة تتغير كلما اقترب موعد المغادرة، محسوبة على تاريخ مغادرتك أنت، فترى موقعك بالضبط في أي يوم.' },
      { q: 'كم يستغرق الاسترداد؟',
        a: 'يعتمد على المورّد وطريقة الدفع، ولن ننشر متوسطًا لا نملك دليلًا عليه بعد. سنعطيك المدة المتوقعة كتابةً مع شروطك.' },
      { q: 'شركة الطيران غيّرت موعد رحلتي، ماذا أفعل؟',
        a: 'أخبرنا. تغييرات الجدول تأتي من الناقل، وما تستحقه يعتمد على حجم التغيير. نحن نتولى المراسلات.' },
      { q: 'حدث خطأ في الرحلة، إلى من أشتكي؟',
        a: 'إلى الشخص الذي تولّى حجزك أولًا. وإن لم يُحل الأمر، اطلب تصعيده وسنخبرك من يتولاه ومتى.' },
    ],
  },
  {
    id: 'documents',
    title: 'التأشيرات والجوازات والوثائق',
    blurb: 'الجزء الذي يسبب أكبر قلق، مُجاب حسب الجواز.',
    items: [
      { q: 'هل أحتاج تأشيرة؟',
        a: 'يعتمد على الجواز الذي تحمله لا على مكان إقامتك. كل صفحة رحلة تذكر وضع التأشيرة للوجهة مع تاريخ آخر تحقق، لأن هذه القواعد تتغير دون إشعار.' },
      { q: 'لماذا التأشيرة «غير مشمولة» وهي مجانية؟',
        a: 'لأن «غير مشمول» تعني خارج الباقة لا بالضرورة مكلفًا. وحيث تكون الوجهة بلا تأشيرة لجواز خليجي نذكرها بصفر ونقولها، بدل حذفها وتركك تتساءل.' },
      { q: 'كم مدة صلاحية الجواز المطلوبة؟',
        a: 'أغلب الوجهات هنا تطلب ستة أشهر بعد تاريخ عودتك. ونؤكد الشرط لمسارك تحديدًا في عرض السعر.' },
      { q: 'متى تطلبون رقم الجواز؟',
        a: 'ليس عند الطلب، ولا لعرض سعر عليك. تُجمع بيانات الوثائق قرب موعد المغادرة عبر رابط آمن، لأن الاحتفاظ بوثائق الهوية أطول من اللازم خطر عليك وعلينا.' },
      { q: 'هل تتولون طلب التأشيرة عني؟',
        a: 'حيث تسمح الوجهة للوكالة بالتقديم نيابة عنك سنذكر ذلك في صفحة الرحلة. وحيث لا تسمح، نخبرك بما تقدّمه وكم يستغرق تقريبًا.' },
    ],
  },
  {
    id: 'faith-family',
    title: 'الطعام الحلال والصلاة والسفر العائلي',
    blurb: 'مذكورة كوقائع تحققنا منها لا كشارة.',
    items: [
      { q: 'هل الفندق مناسب للمسلمين؟',
        a: 'هذا ليس سؤالًا واحدًا، فلا نجيبه بشارة واحدة. كل رحلة تحمل حالات منفصلة: مطاعم حلال قريبة، مصلّى، هل الفندق بلا كحول، وهل يوجد قسم عائلي. وكل حالة تذكر من تحقق منها ومتى.' },
      { q: 'ماذا تعني العلامات الخضراء والكهرمانية والحمراء؟',
        a: 'الأخضر متحقق منه وموجود. والكهرماني جزئي أو مشروط، والملاحظة تشرح كيف. والأحمر متحقق من غيابه، ونفضّل إخبارك على أن تكتشفه. والرمادي يعني لم يتحقق منه أحد بعد، ولن نلوّنه.' },
      { q: 'هل يمكن إيجاد مسبح أو شاطئ للنساء فقط؟',
        a: 'اسأل، ونتحقق للفندق والتاريخ تحديدًا. فهذه مسألة توفر حقيقية لا صفة دائمة للفندق.' },
      { q: 'نسافر مع الأجداد وأطفال صغار، هل تتولون ذلك؟',
        a: 'نعم، ولهذا يصل عدّاد المسافرين في كل رحلة إلى اثني عشر. أخبرنا بالأعمار ومن يحتاج أن يكون بجوار من، وتذهب الغرف المتصلة وملاحظات الحركة مع الطلب.' },
      { q: 'هل تبيعون باقات عمرة أو حج؟',
        a: 'لا. كلاهما منتج منظّم يتطلب ترخيصًا من وزارة الحج والعمرة السعودية، وبيعه كحزمة طيران وفندق عادية تعرّض قانوني لا اختصار. نقولها بوضوح بدل قبول الحجز بصمت.' },
    ],
  },
  {
    id: 'travel',
    title: 'الطيران والحقائب والتنقل',
    blurb: 'تفاصيل الرحلة نفسها.',
    items: [
      { q: 'من أي مطار أغادر؟',
        a: 'مدينة المغادرة جزء من الرحلة لا مرشّح تطبّقه لاحقًا. كل سعر محسوب من تلك المدينة، فرحلة من جدة ونفس الوجهة من دبي تُسعّران على حدة.' },
      { q: 'هل الحقيبة المشحونة مشمولة؟',
        a: 'هي بند في دفتر كل رحلة، إما مشمولة أو مذكورة بتقدير ومصدره. الناقلون يختلفون ولا نأخذ متوسطًا.' },
      { q: 'هل التوصيل من المطار مشمول؟',
        a: 'حيث يكون متعاقدًا عليه، نعم، والدفتر يقولها. وحيث لا يكون، يذكره الدفتر بتقدير بدل حذفه.' },
      { q: 'هل أختار الفندق والرحلة بالتحديد؟',
        a: 'أخبرنا بما تريد ونسعّره. الكتالوج نقطة بداية لا سياج.' },
      { q: 'هل ترتبون تأمين السفر؟',
        a: 'نخبرك بما يجب أن تغطيه الوثيقة لمسارك. ولا نبيع التأمين على هذا الموقع.' },
    ],
  },
  {
    id: 'account',
    title: 'حسابك وبياناتك',
    blurb: 'ما نحتفظ به، وما تستطيع إلزامنا به.',
    items: [
      { q: 'هل أحتاج حسابًا لرؤية الأسعار؟',
        a: 'لا. لا شيء هنا خلف تسجيل دخول، ولا يوجد سعر خاص بالأعضاء. الحساب ليجد طلباتك مرة أخرى لا ليفتح رقمًا.' },
      { q: 'ما الذي تخزنونه فعلًا؟',
        a: 'ما ترسله: الرحلة التي سألت عنها، وتواريخك ومجموعتك، ووسيلة للرد عليك. وثائق الهوية تُجمع قرب المغادرة وبشكل منفصل.' },
      { q: 'هل يمكنكم حذف بياناتي؟',
        a: 'نعم. اطلب، ونؤكد لك ما حُذف وما نحن ملزمون بالاحتفاظ به ولأي مدة.' },
      { q: 'أين تُحفظ بياناتي؟',
        a: 'خارج الخليج، على بنية تحتية مُدارة، لأن مزود قاعدة البيانات لدينا لا يملك منطقة في الشرق الأوسط. هذا إفصاح لا هامش، وهو الجواب الصادق لسؤال لا يُجاب عادة.' },
      { q: 'هل تستخدمون ملفات الارتباط؟',
        a: 'فقط ما يحتاجه الموقع ليعمل، ما لم تخبرنا بغير ذلك. ورفض البقية إجراء واحد ولا يعطّل شيئًا جئت من أجله.' },
    ],
  },
  {
    id: 'about',
    title: 'عن هذا الموقع',
    blurb: 'ما هذا، بصراحة.',
    items: [
      { q: 'هل هذه رحلات وأسعار حقيقية؟',
        a: 'لا، والموقع يقولها على كل بطاقة. هذا كتالوج تجريبي: الباقات متخيلة تحت علامة متخيلة حتى يُعرض التصميم وسلوك التسعير وهما يعملان. كل سعر يحمل علامة «تجريبي»، ولا شيء في الموقع يستطيع أن يقول «احجز».' },
      { q: 'لماذا بُني هكذا؟',
        a: 'لأن البديل أسوأ. موقع عرض يظهر رقم ترخيص لا يملكه، أو تقييمات من عملاء غير موجودين، ليس تصميمًا أضعف بل سجل مزوّر. فتُركت غائبة بدل أن تُملأ.' },
      { q: 'ماذا يعني اسم «أنيس»؟',
        a: 'الأنيس هو الرفيق الذي تأنس به، من الأُنس. يُكتب «أنيس» بالعربية و«Anees» في غيرها، ولا يُترجم إلى أي لغة.' },
      { q: 'بأي لغات تعملون؟',
        a: 'العربية والإنجليزية، مكتوبتان لا مترجمتان آليًا، والفرنسية قيد العمل ومعلّمة كذلك في قائمة اللغات.' },
    ],
  },
];

const FR: FaqCategory[] = [
  {
    id: 'prices',
    title: 'Prix et ce qui est inclus',
    blurb: 'Ce que le chiffre signifie avant même de nous contacter.',
    items: [
      { q: 'Le prix est-il par personne ou pour tout le groupe ?',
        a: "Chaque montant sur la page d'un voyage est le prix complet pour le groupe que vous indiquez. Changez le nombre de voyageurs et le chiffre suit. Le prix par personne et par nuit figurent en dessous, pour comparer honnêtement des séjours de durées différentes." },
      { q: 'Les taxes et les frais sont-ils déjà compris ?',
        a: "Oui. Les taxes et frais obligatoires sont calculés avant que vous ne voyiez le montant. Aucune étape ultérieure ne le fait augmenter." },
      { q: 'À quoi sert alors la liste « non inclus » ?',
        a: "Aux éléments réellement hors forfait : frais de visa, bagage en soute chez un transporteur qui le facture, transfert aéroport non contractualisé. Chacun est nommé, chiffré, avec l'origine de l'estimation. Mieux vaut le voir ici qu'à la fin." },
      { q: 'Pourquoi le prix change-t-il quand je modifie le nombre de nuits ?',
        a: "Parce que ce n'est plus le voyage que nous vendons. Un forfait est un nombre de nuits contractualisé ; dès que vous en sortez, le chiffre devient une estimation calculée au tarif par nuit, et il est présenté comme telle. Une personne confirme le montant réel avant tout engagement." },
      { q: 'Affichez-vous un prix barré ?',
        a: "Non. Nous n'affichons pas un prix de référence qui n'a jamais été pratiqué, ni compte à rebours, ni « trois personnes regardent ». Si un départ est réellement limité, nous donnons le vrai chiffre." },
      { q: 'Dans quelle devise vois-je les prix ?',
        a: "Dans celle de votre ville de départ. Un voyage au départ du Koweït est affiché en dinar koweïtien, qui compte trois décimales, et nous l'affichons avec trois plutôt que d'arrondir à deux." },
    ],
  },
  {
    id: 'enquiry',
    title: 'Demande et devis',
    blurb: "Ce qui se passe entre votre question et votre décision.",
    items: [
      { q: 'Puis-je réserver en ligne tout de suite ?',
        a: "Non, et c'est un choix, pas un manque. Vous envoyez une demande, une personne la traite et revient vers vous avec un devis ferme. Rien sur ce site n'encaisse de paiement." },
      { q: 'La demande est-elle payante ?',
        a: "Non. Aucun frais à aucun moment sur ce site." },
      { q: 'Que reçois-je, et quand ?',
        a: "Un devis écrit pour le groupe et les dates demandés, avec le même montant tout compris et la même liste d'exclusions que sur la page. Les délais de réponse suivent nos horaires publiés plutôt qu'une promesse intenable." },
      { q: 'Combien de temps un devis reste-t-il valable ?',
        a: "Chaque devis porte une date d'expiration visible. À l'échéance la page ne disparaît pas : le devis s'affiche barré, avec un moyen d'en demander un nouveau." },
      { q: 'Suis-je engagé dès la demande ?',
        a: "Non. Une demande est une question. Rien ne vous engage tant que des conditions ne vous ont pas été remises et que vous ne les avez pas acceptées par écrit." },
      { q: 'Peut-on échanger sur WhatsApp plutôt que par formulaire ?',
        a: "Oui, et c'est ainsi que l'essentiel se passe. Le voyage, vos dates et votre groupe accompagnent le message : rien à ressaisir." },
    ],
  },
  {
    id: 'changes',
    title: 'Modification, annulation et remboursement',
    blurb: 'Ce qui se passe quand les plans bougent.',
    items: [
      { q: 'Puis-je changer les dates ou le groupe après ma demande ?',
        a: "Avant confirmation, oui, librement : dites-le nous et nous refaisons le devis. Après confirmation, cela dépend des fournisseurs concernés, et le devis énonce ces conditions avant votre acceptation." },
      { q: "Quelle est la politique d'annulation ?",
        a: "Chaque voyage porte un barème de remboursement daté plutôt qu'un paragraphe dans un PDF : un pourcentage qui évolue à mesure que le départ approche, calculé sur votre propre date de départ." },
      { q: 'Combien de temps prend un remboursement ?',
        a: "Cela dépend du fournisseur et du moyen de paiement, et nous ne publierons pas une moyenne que nous ne pouvons pas encore prouver. Le délai attendu vous sera donné par écrit avec vos conditions." },
      { q: "La compagnie aérienne a modifié mon vol. Que faire ?",
        a: "Prévenez-nous. Les changements d'horaire viennent du transporteur, et vos droits dépendent de l'ampleur du changement. Nous prenons en charge les échanges." },
      { q: "Quelque chose s'est mal passé. À qui m'adresser ?",
        a: "D'abord à la personne qui a traité votre dossier. Si cela ne suffit pas, demandez une escalade : nous vous dirons qui la traite et sous quel délai." },
    ],
  },
  {
    id: 'documents',
    title: 'Visas, passeports et documents',
    blurb: "La partie la plus anxiogène, répondue selon votre passeport.",
    items: [
      { q: "Ai-je besoin d'un visa ?",
        a: "Cela dépend du passeport que vous détenez, pas de votre lieu de résidence. Chaque page indique la situation du visa pour la destination, avec la date de dernière vérification, car ces règles changent sans préavis." },
      { q: 'Pourquoi le visa est-il « non inclus » s\'il est gratuit ?',
        a: "Parce que « non inclus » veut dire hors forfait, pas nécessairement coûteux. Là où la destination est sans visa pour un passeport du Golfe, nous l'indiquons à zéro et le disons, plutôt que de l'omettre." },
      { q: 'Quelle validité de passeport faut-il ?',
        a: "La plupart des destinations ici demandent six mois au-delà de votre date de retour. Nous confirmons l'exigence pour votre itinéraire précis dans le devis." },
      { q: 'Quand demandez-vous mon numéro de passeport ?',
        a: "Ni à la demande, ni pour vous afficher un prix. Les documents sont collectés près du départ via un lien sécurisé, car conserver des pièces d'identité plus longtemps que nécessaire est un risque pour vous comme pour nous." },
      { q: 'Faites-vous la demande de visa à ma place ?',
        a: "Là où la destination permet à une agence de déposer pour vous, nous l'indiquons sur la page du voyage. Sinon, nous vous disons quoi déposer et combien de temps cela prend environ." },
    ],
  },
  {
    id: 'faith-family',
    title: 'Halal, prière et voyage en famille',
    blurb: "Traité comme des faits vérifiés, pas comme un badge.",
    items: [
      { q: "L'hôtel est-il adapté aux voyageurs musulmans ?",
        a: "Ce n'est pas une seule question, donc nous n'y répondons pas par un seul badge. Chaque voyage porte des états distincts : restauration halal à proximité, salle de prière, établissement sans alcool, espace familial. Chaque état nomme qui l'a vérifié et quand." },
      { q: 'Que signifient les marques verte, ambre et rouge ?',
        a: "Vert : vérifié présent. Ambre : partiel ou conditionnel, la note explique comment. Rouge : vérifié absent, et nous préférons vous le dire. Gris : personne ne l'a encore vérifié, et nous ne le colorierons pas." },
      { q: 'Pouvez-vous trouver une piscine ou une plage réservée aux femmes ?',
        a: "Demandez, et nous vérifions pour l'établissement et la date précis. C'est une vraie question de disponibilité, pas une caractéristique permanente d'un hôtel." },
      { q: 'Nous voyageons avec les grands-parents et de jeunes enfants. Est-ce possible ?',
        a: "Oui, et c'est pourquoi le compteur de voyageurs va jusqu'à douze. Indiquez les âges et qui doit être à côté de qui : chambres communicantes et contraintes de mobilité partent avec la demande." },
      { q: 'Vendez-vous des forfaits Omra ou Hajj ?',
        a: "Non. Ce sont des produits réglementés exigeant une licence du ministère saoudien du Hajj et de la Omra ; les vendre comme un simple ensemble vol et hôtel serait une exposition juridique, pas un raccourci. Nous le disons clairement plutôt que d'accepter la réservation en silence." },
    ],
  },
  {
    id: 'travel',
    title: 'Vols, bagages et déplacements',
    blurb: 'La mécanique du voyage lui-même.',
    items: [
      { q: "De quel aéroport est-ce que je pars ?",
        a: "La ville de départ fait partie du voyage, ce n'est pas un filtre appliqué après coup. Chaque prix est calculé depuis cette ville : un départ de Djeddah et la même destination depuis Dubaï sont tarifés séparément." },
      { q: 'Un bagage en soute est-il inclus ?',
        a: "Il figure au registre de chaque voyage, soit inclus, soit indiqué avec une estimation et sa source. Les transporteurs diffèrent et nous n'en faisons pas la moyenne." },
      { q: "Les transferts aéroport sont-ils inclus ?",
        a: "Là où ils sont contractualisés, oui, et le registre le dit. Sinon, le registre les nomme avec une estimation plutôt que de les omettre." },
      { q: "Puis-je choisir l'hôtel et le vol précis ?",
        a: "Dites-nous ce que vous voulez et nous le chiffrons. Le catalogue est un point de départ, pas une clôture." },
      { q: "Proposez-vous une assurance voyage ?",
        a: "Nous vous dirons ce qu'une police doit couvrir pour votre itinéraire. Nous ne vendons pas d'assurance sur ce site." },
    ],
  },
  {
    id: 'account',
    title: 'Votre compte et vos données',
    blurb: 'Ce que nous détenons, et ce que vous pouvez exiger.',
    items: [
      { q: "Faut-il un compte pour voir les prix ?",
        a: "Non. Rien ici n'est derrière une connexion, et il n'existe pas de tarif réservé aux membres. Un compte sert à retrouver vos demandes, pas à débloquer un chiffre." },
      { q: 'Que stockez-vous réellement ?',
        a: "Ce que vous envoyez : le voyage concerné, vos dates et votre groupe, et un moyen de vous répondre. Les pièces d'identité sont collectées près du départ et séparément." },
      { q: 'Pouvez-vous supprimer mes données ?',
        a: "Oui. Demandez-le, et nous confirmerons ce qui a été supprimé, ce que nous sommes tenus de conserver et pour combien de temps." },
      { q: 'Où mes données sont-elles hébergées ?',
        a: "Hors du Golfe, sur une infrastructure gérée, car notre fournisseur de base de données n'a pas de région au Moyen-Orient. C'est une divulgation, pas une note de bas de page." },
      { q: 'Utilisez-vous des cookies ?',
        a: "Seulement ce dont le site a besoin pour fonctionner, sauf indication contraire de votre part. Refuser le reste tient en une action et ne dégrade rien de ce pour quoi vous êtes venu." },
    ],
  },
  {
    id: 'about',
    title: 'À propos de ce site',
    blurb: "Ce que c'est, honnêtement.",
    items: [
      { q: "S'agit-il de vrais voyages à de vrais prix ?",
        a: "Non, et le site le dit sur chaque carte. C'est un catalogue spécimen : les forfaits sont inventés sous une marque inventée, afin de montrer le design et le comportement des prix en fonctionnement. Chaque prix porte la mention « illustratif », et rien sur le site ne peut dire « Réserver »." },
      { q: 'Pourquoi construire ainsi ?',
        a: "Parce que l'alternative est pire. Un site de démonstration affichant un numéro de licence qu'il ne détient pas, ou des avis de clients inexistants, n'est pas un design plus faible : c'est un faux document. Ces éléments sont donc absents plutôt que remplis." },
      { q: 'Que signifie Anees ?',
        a: "C'est de l'arabe. Un anees est le compagnon auprès duquel on se sent bien, de uns, le confort de la bonne compagnie. Il s'écrit أنيس en arabe et Anees ailleurs, et il ne se traduit jamais." },
      { q: 'Dans quelles langues travaillez-vous ?',
        a: "L'arabe et l'anglais, rédigés plutôt que traduits automatiquement, et le français, désormais rédigé également." },
    ],
  },
];

export function faqFor(locale: Locale): FaqCategory[] {
  return locale === 'ar' ? AR : locale === 'fr' ? FR : EN;
}
